language: node_js
node_js:
 - "8"
 - "10"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
  - npm prune
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - echo "No tests, yet" && exit 0
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
